### ISSUE TITLE
Error occurs with the latest update

### ISSUE THREAD

**Issue by Shu-Ji** [angular/angularjs-batarang#156]
![3](https://cloud.githubusercontent.com/assets/1127594/5370152/75d4535c-8059-11e4-938d-657ce8071978.png)

The 1st undefined is:
![4](https://cloud.githubusercontent.com/assets/1127594/5370176/c6f53f76-8059-11e4-8b6f-abc1ea814049.png)

Without AngularJS Batarang, site works fine.

AngularJS Batarang 0.5.0 Dec.9th

angular.version
Object {full: "1.2.25", major: 1, minor: 2, dot: 25, codeName: "hypnotic-gesticulation"}

plnkr: http://plnkr.co/edit/c988Nw?p=preview

**Comment by nbarnwell** [comment]
I had the same issue a few weeks ago, and while it'd be good if it was fixed, I think some people need a little perspective here. This is a free tool they are using by choice. I'm sure @btford is more upset than anyone here that there are problems, but it has to be said that Batarang is worth every penny we're paying for it. @btford Thank you for your hard work to provide what is basically essential functionality for Angular development, and ignore these childish calls of "rollback immediately" etc. Although if you're unable to provide a proper fixed version (has that happened already) perhaps a new version with old code (i.e. rollback or branch from an earlier tag/revision) might buy the time to look into the issues and save the zipfile workaround?

**Comment by Splaktar** [comment]
@nbarnwell no one is asking for a rollback or anything like that anymore as a fully functional workaround has been provided (http://stackoverflow.com/a/27404493/633107).

I'm sure that Brain recognizes how many people are enjoying his extension and relied upon it for their daily development and debugging work. The more success that something gets, the more people will rely on it and be upset if it goes away. 

Plenty of people would be willing to leave some tips via Gratipay (https://gratipay.com/) or PayPal if Brain was interested in that / allowed to.

**Comment by iamlothian** [comment]
As one of the first to throw the stone. I'd happily buy @btford a bear for his work. Make it happen.

**Comment by SergeyBukhman** [comment]
@iamlothian wait a minute. What kind of bear are we talking here? What kind of bear is best?
http://youtu.be/zsGnFExpup8

**Comment by iamlothian** [comment]
Haha caught out. (Autocomplete) If you want a bear I'll have to oblige.
