### ISSUE TITLE
Revert to previous version based on user feedback

### ISSUE THREAD

**Issue by dsaf** [angular/angularjs-batarang#203]
https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk/reviews?hl=en

Last 10 reviews (none skipped):

 > "What happened?! Where's the inspector? Useless now, please fix asap!"

 > "what the heck is this new version, visuals are poor and does not display models correctly, please roll back"

 > "After the latest update, became useless."

 > "But unfortunately the most useful features from the old version no longer seems to exist, or don't work as well."

 > "What the heck? The entire application is missing? Please restore the old version. This new version is not usable, and I think its actually broken. I am not seeing any models at all!"

 > "The last updated causes major performance issues so much so that i've had to disable the extension. Roll it back please."

 > "what happened? I tried using batarang today, it has lost all its features and looks completely different."

 > "This new version is terrible. Before, it used to actually show my heirarchy of scopes, and all the data contained. "

 > "It was great - now it's useless. Nothing seems to work at all."

 > "Update renders this extension useless."

**Comment by demisx** [comment]
I am not sure what the previous version was like, but I've tried to use Batarang today after a few weeks and all of the functionality is gone in 0.7.4. I can only see `Scopes` menu item (that shows no scopes--just blank) and the `Hints` menu item mostly complaining about material design code not following best practices for naming. Can someone please explain what happened?

**Comment by matomesc** [comment]
Same problem with 0.7.4 here - all views are empty, except `Hints`.

**Comment by btford** [comment]
Please see other issues. I'm not really interested in this approach.
