### ISSUE TITLE
Chrome Plugin: Module 'ngLocale' is not available

### ISSUE THREAD

**Issue by renesansz** [angular/angularjs-batarang#204]
Found out that the plugin is not working properly and the caused was that it got an uncaught error:
`Uncaught Error: [$injector:nomod] Module 'ngLocale' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by SomeKittens** [comment]
Did some digging - this is due to `angular-hint-directives` having a hack that's since been removed.  However, this still appears when installing dependencies manually.
