### ISSUE TITLE
Batarang cannot work and show nothing in the Models panel

### ISSUE THREAD

**Issue by wwsun** [angular/angularjs-batarang#212]
HLEP!!! To test my code in Chrome 41 with Angular 1.3.15, I cannot see anything in the Models Panel. Does anyone know the solution?
![batarang](https://cloud.githubusercontent.com/assets/6984035/6933539/26355760-d85b-11e4-893b-4de5db173cdd.PNG)

**Comment by bluedusk** [comment]
0.7.4 same with me, show nothing ~

**Comment by vie02** [comment]
use chrome v 38 or 39 with stable batarang extension on chrome web store, work for me on win 8.1

**Comment by jeblister** [comment]
0.7.4 same with me, show nothing shown i use  chrome v 42

**Comment by SomeKittens** [comment]
Closing as duplicate of #192 (thanks for reporting though!)
