### ISSUE TITLE
Scrolling huge apps in performance tab.

### ISSUE THREAD

**Issue by valimvf** [angular/angularjs-batarang#220]
While you're trying to inspect some huge app. If you're going on performance, at first scroll attempt it melts the proc. I'm not sure if the problem is from scrolling tons of rows, or from updating such huge amount of data. If it's from scroll, try this. http://nexts.github.io/Clusterize.js/

Thanks.

**Comment by SomeKittens** [comment]
Latest doesn't have a performance tab, as it was removed for exactly this reason.  We don't support the so-called "Stable" Batarang, that's a third-party fork you can find here: https://github.com/spalger/angularjs-batarang

**Comment by SomeKittens** [comment]
(A much more performant performance tab will be landing shortly)
