### ISSUE TITLE
All angular expressions being evaluated on load

### ISSUE THREAD

**Issue by charliewynn** [angular/angularjs-batarang#227]
It seems version: 0.8.0 evaluates all of my angular expressions (including ng-click) when they are loaded (so elements are clicked as soon as they appear).

**Comment by SomeKittens** [comment]
I couldn't reproduce with this example: https://gist.github.com/SomeKittens/2d23fd0514cac071e107

Can you provide a small example that demonstrates this behavior?

**Comment by miiihi** [comment]
I can confirm the same behavior with 0.8.0 and only disabling batarang solves the issue. Couldn't isolate the issue. will try maybe later in the week...

**Comment by charliewynn** [comment]
I couldn't reproduce with the sample you linked, but I'm trying to coerce it into breaking, will update if I get anywhere.  For starters I'm on angular 1.2.16

**Comment by charliewynn** [comment]
I'm having trouble getting batarang to do anything in my tests (still works in my big app) - the AngularJS tab in dev tools doesn't show anything under Scopes or Hints.  Is there something specific I need in my app to use batarang?

https://drive.google.com/file/d/0B9TEFzfvelUHdjM1X214VWR2X0E/view

**Comment by SomeKittens** [comment]
This is odd.  We're aware of issues where data sent during bootstrapping (of Batarang) won't be captured ( @erwinmombay is working on this ).

As far as the expressions being evaluated, I can't help much without an example.  Thanks for investigating.

**Comment by charliewynn** [comment]
Yeah, I know it's basically impossible to debug without an example.. Not sure what's actually causing it, my working example is wrapped around a .net app so I don't want to try to strip it down to something I can post

**Comment by SomeKittens** [comment]
@charliewynn I'll keep an eye open for this, hopefully @miiihi has better luck.

**Comment by erwinmombay** [comment]
@charliewynn can you confirm at least that this problem doesn't show up < 0.8 batarang (maybe 0.7.4)? just so we can narrow down at least when the bug cropped up. Thanks!

**Comment by charliewynn** [comment]
I tried checking the changes since the last version, but nothing stuck out as the culprit (spent _maybe_ 10 minutes on it).  All I can really say is everything broke Friday morning, and 0.8.0 came out the day before.  I'm pretty sure I had chrome set to auto-update everything, so I'm fairly confident I was on the latest before that.

**Comment by charliewynn** [comment]
I'm not really sure if this'll help.. trying to dig a little deeper on my end

![image](https://cloud.githubusercontent.com/assets/2472894/8306621/00ee51a4-197f-11e5-85b3-6df88068558c.png)

**Comment by Drstiny** [comment]
I've downloaded Batarang today and encountered this issue.
I have a dropdown menu that is hidden until user logs in. As soon as I logged in with Batarang on, it fired the logout method that is within ng-click in the menu and immediately logged me out.
In the Hints, a new Event appeared: "logout(); is undefined".
The button looks like this: `<li><a href="" ng-click="logout();">{{'Logout' | translate}}</a></li>`. Removing the semicolon actually fixed the issue and the button remained functional.

**Comment by SomeKittens** [comment]
@Drstiny Awesome!  Good find.  Was able to repro with this updated gist: https://gist.github.com/SomeKittens/2d23fd0514cac071e107

**Comment by erwinmombay** [comment]
thanks @Drstiny ! that was super helpful! we'll try and get a fix out soon!

**Comment by Drstiny** [comment]
Glad I could be of help :)

**Comment by SomeKittens** [comment]
PR here with the fix: https://github.com/angular/angular-hint/pull/97

Turns out this has always been a problem, not just 0.8

**Comment by skidvd** [comment]
Same issue here.  Glad to read that a fix is on the way!

**Comment by SomeKittens** [comment]
@skidvd We usually release on Thursdays, so you don't have long to go!  We're also working on a faster release cycle, but everything takes time...

**Comment by skidvd** [comment]
This appears to no longer be an issue as of 0.8.3.  Thanks!
