### ISSUE TITLE
need update version no.

### ISSUE THREAD

**Issue by yhsiang** [angular/angularjs-batarang#90]
there are two commits in 7/9
a5ecad55fdd23f696ff8c547f73e587d51ca26c0 and 49a130c53b7df4fa572e10dbcb76f2111622f80f
and my batarang fails because not patch this one a5ecad55fdd23f696ff8c547f73e587d51ca26c0
so when will make those changes on chrome store?

**Comment by btford** [comment]
There have since been releases. Closing this.
